package passwdmaker;

import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.Toolkit;

public class PasswdJFrame extends javax.swing.JFrame
{
    private PasswdGenerator passwdGen;
    
    /**
     * Creates new form PasswdJFrame
     */
    public PasswdJFrame()
    {
        initComponents();
        
        passwdGen = new PasswdGenerator();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hashAlgorithmButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        urlJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lengthJTextField = new javax.swing.JTextField();
        passwdJButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        showJCheckBox = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        md5sumJTextField = new javax.swing.JTextField();
        passwdJPasswordField = new javax.swing.JPasswordField();
        masterJPasswordField = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        MD5JRadioButton = new javax.swing.JRadioButton();
        SHA1JRadioButton = new javax.swing.JRadioButton();
        SHA256JRadioButton = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        lowerJCheckBox = new javax.swing.JCheckBox();
        upperJCheckBox = new javax.swing.JCheckBox();
        numbersJCheckBox = new javax.swing.JCheckBox();
        specialJCheckBox = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PasswdMaker");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jTabbedPane2.setBackground(new java.awt.Color(51, 51, 51));
        jTabbedPane2.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("master passwd: ");

        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("url: ");

        urlJTextField.setBackground(new java.awt.Color(247, 247, 247));
        urlJTextField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        urlJTextField.setForeground(new java.awt.Color(0, 0, 0));
        urlJTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("length: ");

        lengthJTextField.setBackground(new java.awt.Color(247, 247, 247));
        lengthJTextField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lengthJTextField.setForeground(new java.awt.Color(0, 0, 0));
        lengthJTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        passwdJButton.setBackground(new java.awt.Color(77, 77, 77));
        passwdJButton.setForeground(new java.awt.Color(204, 204, 204));
        passwdJButton.setText("GET");
        passwdJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwdJButtonMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(233, 233, 233));

        jLabel4.setText("passwd");

        showJCheckBox.setBackground(new java.awt.Color(232, 232, 232));
        showJCheckBox.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        showJCheckBox.setText("show passwd");
        showJCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                showJCheckBoxStateChanged(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(232, 232, 232));
        jLabel5.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("md5sum: ");

        md5sumJTextField.setBackground(new java.awt.Color(232, 232, 232));
        md5sumJTextField.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        md5sumJTextField.setForeground(new java.awt.Color(0, 0, 0));
        md5sumJTextField.setBorder(null);
        md5sumJTextField.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        md5sumJTextField.setEnabled(false);

        passwdJPasswordField.setBackground(new java.awt.Color(232, 232, 232));
        passwdJPasswordField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        passwdJPasswordField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(3, 3, 3)
                        .addComponent(md5sumJTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 145, Short.MAX_VALUE)
                        .addComponent(showJCheckBox)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(passwdJPasswordField))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwdJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(showJCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(md5sumJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        masterJPasswordField.setBackground(new java.awt.Color(247, 247, 247));
        masterJPasswordField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        masterJPasswordField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(passwdJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(masterJPasswordField)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(urlJTextField))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lengthJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(masterJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(urlJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lengthJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(passwdJButton)
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("passwd", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(112, 112, 112));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("  Hash Algorithm");
        jLabel6.setOpaque(true);

        MD5JRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        hashAlgorithmButtonGroup.add(MD5JRadioButton);
        MD5JRadioButton.setText("MD5");

        SHA1JRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        hashAlgorithmButtonGroup.add(SHA1JRadioButton);
        SHA1JRadioButton.setText("SHA-1");

        SHA256JRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        hashAlgorithmButtonGroup.add(SHA256JRadioButton);
        SHA256JRadioButton.setSelected(true);
        SHA256JRadioButton.setText("SHA-256");

        jLabel7.setBackground(new java.awt.Color(112, 112, 112));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("  Charsets");
        jLabel7.setOpaque(true);

        lowerJCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        lowerJCheckBox.setSelected(true);
        lowerJCheckBox.setText("lowercase letters (a-z)");

        upperJCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        upperJCheckBox.setSelected(true);
        upperJCheckBox.setText("uppercase letters (A-Z)");

        numbersJCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        numbersJCheckBox.setSelected(true);
        numbersJCheckBox.setText("numbers (0-9)");

        specialJCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        specialJCheckBox.setSelected(true);
        specialJCheckBox.setText("special characters");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(specialJCheckBox)
                    .addComponent(numbersJCheckBox)
                    .addComponent(upperJCheckBox)
                    .addComponent(SHA256JRadioButton)
                    .addComponent(SHA1JRadioButton)
                    .addComponent(MD5JRadioButton)
                    .addComponent(lowerJCheckBox))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MD5JRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SHA1JRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SHA256JRadioButton)
                .addGap(33, 33, 33)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(lowerJCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(upperJCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numbersJCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(specialJCheckBox)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("settings", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setBackground(new java.awt.Color(112, 112, 112));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("  About PasswdMaker");
        jLabel8.setOpaque(true);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("PasswdMaker is a simple, open source, password\nmanagement tool.\n\nBased on the concept of PasswordMaker:\nhttp://passwordmaker.org/Introduction\n\nHomepage: http://panosrcng.no-ip.org/?p=73\n\nGet the source code from GitHub:\nhttps://github.com/PanosRCng/PasswdMaker");
        jTextArea1.setBorder(null);
        jTextArea1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextArea1.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/passwdmaker/logo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(20, 20, 20))
        );

        jTabbedPane2.addTab("about", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwdJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwdJButtonMouseClicked
        
        String master = masterJPasswordField.getText();
        String url = urlJTextField.getText();
        String length = lengthJTextField.getText();
        
        String[] args = new String[]{master, url, length};
        
        if( validate_inputs(args) )
	{
            String passwd = get_passwd(args);

            HashGenerator hashGen = new HashGenerator( "MD5" );
            String md5sum = hashGen.getHash( passwd );
            
            passwdJPasswordField.setText(passwd);
            md5sumJTextField.setText(md5sum);
            
            copyToClipBoard(passwd);
        }
        
    }//GEN-LAST:event_passwdJButtonMouseClicked

    private void showJCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_showJCheckBoxStateChanged
        
        if( showJCheckBox.isSelected() )
        {
            passwdJPasswordField.setEchoChar((char)0);
        }
        else
        {
            passwdJPasswordField.setEchoChar('•');
        }
        
    }//GEN-LAST:event_showJCheckBoxStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswdJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswdJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswdJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswdJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasswdJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton MD5JRadioButton;
    private javax.swing.JRadioButton SHA1JRadioButton;
    private javax.swing.JRadioButton SHA256JRadioButton;
    private javax.swing.ButtonGroup hashAlgorithmButtonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField lengthJTextField;
    private javax.swing.JCheckBox lowerJCheckBox;
    private javax.swing.JPasswordField masterJPasswordField;
    private javax.swing.JTextField md5sumJTextField;
    private javax.swing.JCheckBox numbersJCheckBox;
    private javax.swing.JButton passwdJButton;
    private javax.swing.JPasswordField passwdJPasswordField;
    private javax.swing.JCheckBox showJCheckBox;
    private javax.swing.JCheckBox specialJCheckBox;
    private javax.swing.JCheckBox upperJCheckBox;
    private javax.swing.JTextField urlJTextField;
    // End of variables declaration//GEN-END:variables


    private boolean validate_inputs(String[] args)
    {
	for(int i=0; i<args.length; i++)
	{
            if( (args[i].length()==0) || (args[i].length() > 256) )
            {
		return false;
            }
	}

	try
	{
            if( Integer.parseInt(args[2]) < 8)
            {
		return false;
            }
	}
	catch( NumberFormatException ex )
	{
            return false;
	}

	return true;
    }
    
    private String get_passwd(String[] args)
    {
        HashGenerator hashGen = new HashGenerator( getHashAlgorithm() );

	String hash = hashGen.getHash( args[0] + args[1] + args[2] );

	return passwdGen.getPasswd(hash, getCharsets(), Integer.parseInt(args[2]));
    }
    
    
    private String getHashAlgorithm()
    {
        if( MD5JRadioButton.isSelected() )
        {
            return "MD5";
        }
        else if( SHA1JRadioButton.isSelected() )
        {
            return "SHA-1";
        }
        
        return "SHA-256";
    }
    
    
    private int[] getCharsets()
    {
        int[] charsets = new int[] {-1,-1,-1,-1};
        
        if( lowerJCheckBox.isSelected() )
        {
            charsets[0] = 1;
        }
        
        if( upperJCheckBox.isSelected() )
        {
            charsets[1] = 2;
        }
        
        if( numbersJCheckBox.isSelected() )
        {
            charsets[2] = 3;
        }
        
        if( specialJCheckBox.isSelected() )
        {
            charsets[3] = 4;
        }
        
        return charsets;
    }
    
    
    private void copyToClipBoard(String passwd)
    {
        StringSelection stringSelection = new StringSelection(passwd);
        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
        clpbrd.setContents(stringSelection, null);
    }
    
}
